config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'blogs#index'
  resources :blogs, except: [:show] do
    get 'date/:date', to: 'blogs#show_by_date', on: :collection, as: 'show_by_date', constraints: { date: /\d{4}-\d{2}-\d{2}/ }
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :user

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :blogs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: :index
  before_action :move_to_index, except: [:index, :show]

  def index
    @blog = Blog.new
  
    # クエリパラメータからstart_dateを取得して、その月の範囲を指定して合計金額を取得
    @start_date = params[:start_date].present? ? Date.parse(params[:start_date]).beginning_of_month : Date.current.beginning_of_month
    @end_date = @start_date.end_of_month
    @total_expenses = current_user.blogs.where(start_time: @start_date..@end_date).sum(:price)
  
    # カレンダーの表示月を指定して予定データを取得
    @blogs = current_user.blogs.where(start_time: @start_date..@end_date)
  end
  
  
  def new
    @blog = Blog.new
  end

  def show_by_date
    date = Date.parse(params[:date])
    @blogs = Blog.where(start_time: date.beginning_of_day..date.end_of_day)
  
    if @blogs.any?
      render 'show'
    else
      redirect_to blogs_path, alert: "選択した日に予定はありませんでした"
    end
  end
  
  def show
    @blog = Blog.find(params[:id])
    #@schedules = @blog.schedules
  end

  def create
    @blog = current_user.blogs.build(blog_parameter)
  
    if @blog.save
      redirect_to blogs_path, notice: '予定を追加しました。'
    else
      render :new
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.price = params[:blog][:price]
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end
  

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time, :price).merge(user_id: current_user.id)
  end
  

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def destroy
    sign_out
    redirect_to root_path, status: :see_other
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_header.html.erb
<div class="header">
  <%= image_tag("タイトル.png", alt: "カレンダータイトルロゴ", class: "title-logo") %>
 <br>
 <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout-link" %>
</div>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title1">
    <div class="form-tag1">タイトル</div>
    <%= form.text_field :title, class: "form-input1" %>
  </div>


  <div class="content1">
    <div class="form-tag1">内容</div>
    <%= form.text_field :content, class: "form-input1" %>
  </div>

  <div class="price1">
      <div class="form-tag1">費用</div>
      <%= form.text_field :price, pattern: "[0-9]*", inputmode: "numeric", placeholder: "半角英数字を入力", class: "form-input1" %>
  </div>  

    <div class="time1">
    <div class="form-tag1">時間</div>
    <%= form.datetime_select :start_time, class: "form-input1" %>
  </div>


  <div class="submit1">
     <%= form.submit "予定を変更", class: "submit-button1" %>
  </div>

<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<% if flash[:alert] %>
  <div class="alert alert-warning">
    <%= flash[:alert] %>
  </div>
<% end %>


<%= render 'blogs/header' %>

<div class="row">
 <div class="col-md-4">
	 <div class="schedule">今後の予定一覧</div>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>タイトル</th>
        <th>日程</th>
      </tr>
    </thead>
     <tbody>
        <% @blogs.each do |blog| %>
          <tr>
            <td><%= link_to blog.title, blog, class: "table-link" %></td>
            <td><%= blog.start_time.strftime("%m-%d") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="total-expenses">
  <strong><%= @start_date.strftime('%Y年%m月') %> の合計費用：</strong> <span id="total-expenses-value"><%= @total_expenses %> 円</span>
</div>


  </div>
</div>


<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル</div>
    
    <%= form.text_field :title %>
  </div>


  <div class="content">
    <div class="form-tag">内容</div>
    <textarea name="blog[content]" rows="5" class="fixed-size"></textarea>
  </div>

   <div class="price">
      <div class="form-tag">費用</div>
      <%= form.text_field :price, pattern: "[0-9]*", inputmode: "numeric" , placeholder: "半角英数字を入力" %>
  </div>  


  <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

 <div class="submit">
  <%= form.submit "予定を追加" %>
</div>
<% end %>
</div>

<br>
<br>

<div class="col-md-8">
<%= month_calendar events: @blogs do |date, blogs| %>
  <%= link_to date.day, show_by_date_blogs_path(date: date) %>
  <% blogs.each do |blog| %>
    <div>
      <%#<%= link_to blog.title, blog %>
        <%=blog.title %>
    </div>
  <% end %>
<% end %>
</div>
</div>

app/views/blogs/show.html.erb
<p id="notice" class="notice-message"><%= notice %></p>
<div class="schedules">
  <h3 class="schedule-heading">一日のスケジュール</h3>
  <table class="schedule-table">
    <thead>
      <tr>
        <th class="schedule-table__header">時間</th>
        <th class="schedule-table__header">タイトル</th>
        <th class="schedule-table__header">内容</th>
      </tr>
    </thead>

    <tbody>
      <% (0..24).each do |hour| %>
        <tr>
          <td class="schedule-table__time"><%= sprintf("%02d:00", hour) %></td>
          <td class="schedule-table__content" colspan="2">
            <% blogs_for_hour = @blogs.select { |blog| blog.start_time&.hour == hour } %>
            <% if blogs_for_hour.any? %>
              <% blogs_for_hour.each do |blog| %>
                <div class="schedule-entry">
                  <p class="schedule-entry__time">
                    <% if blog.start_time %>
                      <strong><%= blog.start_time.strftime("%H:%M") %></strong>
                    <% else %>
                      <strong>時間未登録</strong>
                    <% end %>
                  </p>
                  <p class="schedule-entry__title"><%= blog.title %></p>
                  <p class="schedule-entry__content"><%= blog.content %></p>
                  <%= link_to '編集', edit_blog_path(blog), class: 'edit-link2' %>
                  <%= link_to '消去', blog_path(blog), data: { turbo_method: :delete }, class: 'delete-link' %>
                </div>
              <% end %>
            <% else %>
              <p class="no-blogs">予定はありません</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to '戻る', blogs_path, class: 'back-link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarCALENDAR</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
 <%= stylesheet_link_tag 'calendar', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/index.html.erb
<h3>一日のスケジュール</h3>

<% @blogs.each do |blog| %>
  <h2><%= blog.title %></h2>
  <p><%= blog.content %></p>
  <p><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></p>
  <hr>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>